__version__ = '0.1.0'
__release__ = __version__ + '-dev'
__authors__ = 'Tyghe Vallard'
__authoremails__ = 'vallardt@gmail.com'
__description__ = 'Various bioinformatics scripting'
__projectname__ = 'bio_pieces'
